export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_PEOPLE_SUCCESS = 'FETCHING_DATA_PEOPLE_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';
export const HASH_MORE ='HASH_MORE';
export const UPDATE_RESULTS = 'UPDATE_RESULTS';
export const FILTER_DATA_SUCCESS = 'FILTER_DATA_SUCCESS';
export const DELETE_ELEMENT =  'DELETE_ELEMENT';